Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the dataset

In [2]:
dataset=pd.read_csv('Housing.csv')
shift=dataset.pop('parking')
dataset.insert(2, 'parking', shift)
Y=dataset.iloc[:,0].values
X=dataset.iloc[:,1:].values

Checking NULL values

In [3]:
if dataset.isnull().any().any():
  print('true')

Encoding the Categorical Values using Label Encoder

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,9]=le.fit_transform(X[:,9])
le1=LabelEncoder()
X[:,5]=le1.fit_transform(X[:,5])
le2=LabelEncoder()
X[:,6]=le2.fit_transform(X[:,6])
le3=LabelEncoder()
X[:,7]=le3.fit_transform(X[:,7])
le4=LabelEncoder()
X[:,8]=le4.fit_transform(X[:,8])
le5=LabelEncoder()
X[:,10]=le5.fit_transform(X[:,10])

Encoding the Categorical variabels using OneHOTEncoding

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[11])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

Printing the Header for cross checks

In [6]:
print(X[:15,])

[[1.0 0.0 0.0 7420 2 4 2 3 1 0 0 0 1 1]
 [1.0 0.0 0.0 8960 3 4 4 4 1 0 0 0 1 0]
 [0.0 1.0 0.0 9960 2 3 2 2 1 0 1 0 0 1]
 [1.0 0.0 0.0 7500 3 4 2 2 1 0 1 0 1 1]
 [1.0 0.0 0.0 7420 2 4 1 2 1 1 1 0 1 0]
 [0.0 1.0 0.0 7500 2 3 3 1 1 0 1 0 1 1]
 [0.0 1.0 0.0 8580 2 4 3 4 1 0 0 0 1 1]
 [0.0 0.0 1.0 16200 0 5 3 2 1 0 0 0 0 0]
 [1.0 0.0 0.0 8100 2 4 1 2 1 1 1 0 1 1]
 [0.0 0.0 1.0 5750 1 3 2 4 1 1 0 0 1 1]
 [1.0 0.0 0.0 13200 2 3 1 2 1 0 1 0 1 1]
 [0.0 1.0 0.0 6000 2 4 3 2 1 1 1 1 0 0]
 [0.0 1.0 0.0 6550 1 4 2 2 1 0 0 0 1 1]
 [1.0 0.0 0.0 3500 2 4 2 2 1 0 0 1 0 0]
 [0.0 1.0 0.0 7800 0 3 2 2 1 0 0 0 0 1]]


NOTE : Furnishing status has came to the start on ONEHOTENCODING

Splitting the Dataset into Training and Test Set

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [8]:
print(X_train)

[[0.0 0.0 1.0 ... 0 1 0]
 [0.0 1.0 0.0 ... 0 0 0]
 [0.0 1.0 0.0 ... 0 0 1]
 ...
 [0.0 0.0 1.0 ... 0 1 1]
 [0.0 0.0 1.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 0 0 1]]


In [9]:
print(X_test)

[[1.0 0.0 0.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 0 0 1]
 [0.0 1.0 0.0 ... 0 1 0]
 ...
 [0.0 0.0 1.0 ... 0 0 0]
 [0.0 0.0 1.0 ... 0 1 1]
 [0.0 0.0 1.0 ... 0 1 0]]


Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc_y=StandardScaler()
X_train[:,3:8]=sc.fit_transform(X_train[:,3:8])
Y_train=sc_y.fit_transform(Y_train.reshape(-1,1))

Training the Multiple Linear Regression model on training Set

In [11]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

Scaling the Test Set

In [12]:
X_test[:,3:8]=sc.transform(X_test[:,3:8])

Predicted values of Test Set

In [13]:
Y_pred=sc_y.inverse_transform((regressor.predict(X_test)).reshape(-1,1))

In [14]:
print(Y_pred)

[[ 3914654.65431523]
 [ 6136038.45388482]
 [ 4535106.97842372]
 [ 7220687.80398318]
 [ 2809902.28340628]
 [ 6932849.09692254]
 [ 3224755.53104289]
 [ 3242117.23083385]
 [ 3489749.89627333]
 [ 8181977.70819841]
 [ 6560029.43825352]
 [ 3685297.46233992]
 [ 3848862.94984422]
 [ 4518659.05230597]
 [ 4049893.15795007]
 [ 1960092.76732248]
 [ 4077306.36814632]
 [ 3704486.7094773 ]
 [ 3284150.81980144]
 [ 4615519.06166606]
 [ 5912163.90394877]
 [ 6358085.45647446]
 [ 4784567.19120961]
 [ 2681973.96915711]
 [ 5306331.95861161]
 [ 5661789.91748967]
 [ 5429691.40449474]
 [ 5554878.39772429]
 [ 5704737.28013046]
 [ 5824441.63132076]
 [ 3399286.3026257 ]
 [ 6480531.12868439]
 [ 7101897.22646609]
 [ 2925037.76623054]
 [ 4536934.52577014]
 [ 5244195.34883343]
 [ 5038596.27236155]
 [ 3748347.8457913 ]
 [ 2884831.72460937]
 [ 3966739.75368811]
 [ 7931603.72173931]
 [ 4876858.33220366]
 [ 6382757.34565109]
 [ 3544576.31666583]
 [ 3837897.66576572]
 [ 6395550.17707601]
 [ 4511348.86292031]
 [ 2706645.85

Score of the Model

In [15]:
from sklearn.metrics import r2_score
r2_score(Y_test,Y_pred)

0.7243995632116299